"""User Auth Tokens

Revision ID: b1238e5f09dc
Revises: 
Create Date: 2024-12-05 19:36:54.575573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1238e5f09dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.alter_column('year',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('awards',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth_token', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('auth_token_expiration', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint("Token Uniqueness", ['auth_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('auth_token_expiration')
        batch_op.drop_column('auth_token')

    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.alter_column('awards',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('year',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
